---
builds:
  - skip: true
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
